sudo: required
language: go

go:
- 1.7.x

addons:
  apt:
    packages:
    - git
    - make
    - curl

env:
  - DOCKER_IMAGE_NAME=cloudposse/route53-kubernetes


services:
- docker

install:
- curl https://glide.sh/get | sh
- make deps
- |-
  docker login \
    --email="$DOCKER_HUB_EMAIL" \
    --username="$DOCKER_HUB_USERNAME" \
    --password="$DOCKER_HUB_PASSWORD"

script:
- make build
- docker build -t $DOCKER_IMAGE_NAME .

after_success:
- |-
  if [ ! -z "$TRAVIS_TAG" ]; then \
    docker tag $DOCKER_IMAGE_NAME  $DOCKER_IMAGE_NAME:$TRAVIS_TAG &&  \
    docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG; \
  fi

- |-
  if [ ! -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then \
    docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:pr-$TRAVIS_PULL_REQUEST_BRANCH && \
    docker push $DOCKER_IMAGE_NAME:pr-$TRAVIS_PULL_REQUEST_BRANCH; \
  fi

- |-
  if [[ -z "$TRAVIS_PULL_REQUEST_BRANCH" && ! -z "$TRAVIS_BRANCH" ]]; then \
    docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TRAVIS_BRANCH && \
    docker push $DOCKER_IMAGE_NAME:$TRAVIS_BRANCH; \
  fi

- |-
  if [[ -z "$TRAVIS_TAG"  &&  -z "$TRAVIS_PULL_REQUEST_BRANCH"  &&  -z "$TRAVIS_BRANCH" ]]; then \
    docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest && \
    docker push $DOCKER_IMAGE_NAME:latest; \
  fi

- |-
  if [[ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]  && [[ "$TRAVIS_BRANCH" == "master" ]]; then \
    docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest && \
    docker push $DOCKER_IMAGE_NAME:latest; \
  fi
